name: Submit OSS view Issue Form (Beta)
description: Submit new HDR UK affiliated open source software
title: '[OSS]: '
labels: submitted
assignees: 
  - susheel
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a new OSS! Please name the issue as `[OSS]: category/name`
  - type: dropdown
    id: main-category
    attributes:
      label: OSS Main Category
      options:
        - Applied Analytics
        - BHF Data Science Centre
        - Better Care
        - Bioinformatics
        - COVID-19
        - Cohort Discovery
        - Gateway
        - Gateway (MVP)
        - HDR UK
        - ICODA
        - National Phenomics Resource
        - National Text Analytics
        - Training
        - Uncategorised
  - type: input
    id: name
    attributes:
      label: Name
      description: Please supply the proposed OSS name
      placeholder: e.g. papers
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL
      description: Please supply the proposed OSS URL
      placeholder: e.g. https://github.com/HDRUK/papers
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please supply a brief description of the OSS
      placeholder: This software calculates the meaning of life, the universe and eveything
  - type: textarea
    id: keywords
    attributes:
      label: Keywords
      description: Please supply a list of relevant keywords (markdown format)
      placeholder: "- foo"
  - type: dropdown
    id: other-categories
    attributes:
      label: OSS Other Categories
      multiple: true
      options:
        - Applied Analytics
        - BHF Data Science Centre
        - Better Care
        - Bioinformatics
        - COVID-19
        - Cohort Discovery
        - Gateway
        - Gateway (MVP)
        - HDR UK
        - ICODA
        - National Phenomics Resource
        - National Text Analytics
        - Training
        - Uncategorised