name: Collect OSS Metrics

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  collect-oss:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Collect OSS Metrics
      env:
        GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python scripts/annotate_oss.py
    
    - name: Generate README from OSS projects
      run: |
        python scripts/generate_readme.py

    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Commit new OSS Metrics
        branch: ${{ github.head_ref }}
        commit_user_name: Susheel Varma
        commit_user_email: susheel.varma@hdruk.ac.uk
        commit_author: Susheel Varma <susheel.varma@hdruk.ac.uk>
