name: Publish OSS from issue

on:
  issues:
    types: ['labeled']

jobs:
  publish-oss:
    # Run only if label == 'triaged'
    if: ${{ github.event.label.name == 'triaged' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate OSS
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.issue.body }}
        run: |
          PROJECT_FILENAME=$(echo "${POST_TITLE}" | awk '{print $2}')
          cat << EOF >> data/oss/${PROJECT_FILENAME}.yaml
          ${POST_BODY}
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "new-oss-${{ github.event.issue.number }}"
          delete-branch: true
          title: "New ${{ github.event.issue.title}}"
          body: |
            Automagically sprouted for publishing.
            Merging will publish to: https://github.com/HDRUK/oss
            Closes #${{ github.event.issue.number }}
          reviewers: "susheel"
          commit-message: "New ${{ github.event.issue.title }}"